### ISSUE TITLE
app crash for screen rotation when  set a protocol user name and nickname put complete

### ISSUE THREAD

**Issue by kr-nahid** [open-keychain/termbot#7] opened 2018-05-22 07:24 UTC
#### Expected behavior
it should not be crash when screen rotation from portrait to landscape mode while set a protocol   
user name and nickname put complete .
#### Actual behavior
when i set protocol user name and nickname and i rotate my phone portrait to landscape mode it occurs crash . 

#### How to reproduce
* download the app
*  open it and  click on (+) then you will be edit host page
* then put user name and nickname
* and rotate your phone from portrait to landscape mode
* note the bug .

> Browser : Term Bot 1.9.2-termbot.2
 Operating system: android 5.1

#### Recording Of The Bug
https://www.youtube.com/watch?v=gZ8eVpprx1o

**Comment by hagau** [comment] 2018-05-22 09:27
Thanks for the report!

I can't reproduce this here (on 7.1.2/8.1). Could you append a backtrace for the crash?

Just in case this is unclear:
You need to actually input a username (the part before the '@') as well as the hostname in the combined username@hostname:port field. The nickname is just the name displayed for this entry in the host list.
(EDIT: Nevertheless, this should not happen upon entering invalid strings. Thanks for the recording by the way, very useful for attempting reproduction :+1: )

**Comment by dschuermann** [comment] 2019-11-18 21:49
Closing. Issues for current release are tracked here: https://github.com/cotechde/termbot/issues

**Closed as completed by dschuermann** 2019-11-18 21:49 UTC
Labels: further information needed
