### ISSUE TITLE
Authentication failure due to wrong subkey selection

### ISSUE THREAD

**Issue by colemickens** [open-keychain/termbot#12] opened 2018-07-23 00:02 UTC
I have the latest TermBot and OpenKeychain installed from F-Droid, but it doesn't seem to work.

When I choose "External Agent", I am able to select my key from OpenKeychain. I can also see that it is the correct subkey from the GPG applet on the Yubikey. It's the same yubikey and subkey that I use on a regular basis from my laptop.

When I attempt to authenticate, I am prompted for my PIN, but regardless of it being correct, I get this output:

```
...
Attempting to authenticate via ssh-agent
Calling ssh-agent: OpenKeychain
Failed to authenticate via ssh-agent
...
```

I have also tested to ensure that I am entering the correct PIN, etc, and I am. I am able to sign/encrypt as expected from the OpenKeychain application with the other subkeys.

**Comment by hagau** [comment] 2018-07-25 13:14
Thanks for the report!
Could you name the model of the device & OS version you tried this on or post a (redacted) stack trace?

**Comment by colemickens** [comment] 2018-07-25 23:53
I'm on a Pixel 2, using a Android P Developer Preview build (PPP4.180612.004).

How do I get a stack trace?

**Comment by dmaroulidis** [comment] 2018-07-26 14:30
I'm experiencing the exact same issue on a Samsung Galaxy S8. Android version: Oreo 8 

I've experienced this on the latest Openkeychain update and the latest beta.

**Comment by colemickens** [comment] 2018-07-30 02:31
The issue persists, even after the OpenKeychain update to 5.2 yesterday. Screenshot for additional effect. The OpenKeychain icon is it telling me it has successfully saved the PIN for the Yubikey I have inserted.

![screenshot_20180729-192534](https://user-images.githubusercontent.com/327028/43374721-f759ad0a-9365-11e8-8057-19e5b751067f.png)

**Comment by hagau** [comment] 2018-07-30 13:40
Sorry for the late reply.
To obtain a stacktrace, install [adb](https://developer.android.com/studio/command-line/adb), run `adb logcat` and look for anything containing the tag 'TB' (`adb logcat | grep 'TB'`). Be careful not to include personal information when posting.

**Comment by colemickens** [comment] 2018-07-31 03:07
This is the only relevant looking log entries from adb:

```
07-30 20:06:13.984 14242 15626 W System.err: *** Error while scrolling up:
07-30 20:06:13.984 14242 15626 W System.err: --- BEGIN STACK TRACE ---
07-30 20:06:13.984 14242 15626 W System.err: java.lang.ArrayIndexOutOfBoundsException: src.length=25 srcPos=0 dst.length=25 dstPos=-1 length=1
07-30 20:06:13.985 14242 15626 W System.err: 	at java.lang.System.arraycopy(Native Method)
07-30 20:06:13.985 14242 15626 W System.err: 	at de.mud.terminal.VDUBuffer.insertLine(VDUBuffer.java:421)
07-30 20:06:13.985 14242 15626 W System.err: 	at de.mud.terminal.vt320.putChar(vt320.java:1733)
07-30 20:06:13.985 14242 15626 W System.err: 	at de.mud.terminal.vt320.putString(vt320.java:126)
07-30 20:06:13.985 14242 15626 W System.err: 	at de.mud.terminal.vt320.putString(vt320.java:80)
07-30 20:06:13.985 14242 15626 W System.err: 	at org.connectbot.service.TerminalBridge.outputLine(TerminalBridge.java:336)
07-30 20:06:13.985 14242 15626 W System.err: 	at org.connectbot.transport.SSH.authenticate(SSH.java:313)
07-30 20:06:13.985 14242 15626 W System.err: 	at org.connectbot.transport.SSH.connect(SSH.java:537)
07-30 20:06:13.985 14242 15626 W System.err: 	at org.connectbot.service.TerminalBridge$3.run(TerminalBridge.java:290)
07-30 20:06:13.985 14242 15626 W System.err: 	at java.lang.Thread.run(Thread.java:764)
07-30 20:06:13.985 14242 15626 W System.err: --- END STACK TRACE ---
07-30 20:06:13.985 14242 15626 W System.err: bufSize=25, maxBufSize=25
07-30 20:06:13.985 14242 15626 W System.err: top=0, bottom=9
07-30 20:06:13.985 14242 15626 W System.err: n=1, l=9
07-30 20:06:13.985 14242 15626 W System.err: screenBase=0, windowBase=0
07-30 20:06:13.985 14242 15626 W System.err: newScreenBase=0, newWindowBase=0
07-30 20:06:13.985 14242 15626 W System.err: oldBase=0
07-30 20:06:13.986 14242 15626 W System.err: size.width=112, size.height=10
07-30 20:06:13.986 14242 15626 W System.err: abuf.length=25, cbuf.length=25
07-30 20:06:13.986 14242 15626 W System.err: *** done dumping debug information
07-30 20:06:14.007 14242 15626 W System.err: *** Error while scrolling up:
07-30 20:06:14.007 14242 15626 W System.err: --- BEGIN STACK TRACE ---
07-30 20:06:14.007 14242 15626 W System.err: java.lang.ArrayIndexOutOfBoundsException: src.length=25 srcPos=0 dst.length=25 dstPos=-1 length=1
07-30 20:06:14.008 14242 15626 W System.err: 	at java.lang.System.arraycopy(Native Method)
07-30 20:06:14.008 14242 15626 W System.err: 	at de.mud.terminal.VDUBuffer.insertLine(VDUBuffer.java:421)
07-30 20:06:14.008 14242 15626 W System.err: 	at de.mud.terminal.vt320.putChar(vt320.java:1733)
07-30 20:06:14.008 14242 15626 W System.err: 	at de.mud.terminal.vt320.putString(vt320.java:126)
07-30 20:06:14.008 14242 15626 W System.err: 	at de.mud.terminal.vt320.putString(vt320.java:80)
07-30 20:06:14.008 14242 15626 W System.err: 	at org.connectbot.service.TerminalBridge.outputLine(TerminalBridge.java:336)
07-30 20:06:14.008 14242 15626 W System.err: 	at org.connectbot.transport.SSH.authenticate(SSH.java:318)
07-30 20:06:14.008 14242 15626 W System.err: 	at org.connectbot.transport.SSH.connect(SSH.java:537)
07-30 20:06:14.008 14242 15626 W System.err: 	at org.connectbot.service.TerminalBridge$3.run(TerminalBridge.java:290)
07-30 20:06:14.008 14242 15626 W System.err: 	at java.lang.Thread.run(Thread.java:764)
07-30 20:06:14.008 14242 15626 W System.err: --- END STACK TRACE ---
07-30 20:06:14.008 14242 15626 W System.err: bufSize=25, maxBufSize=25
07-30 20:06:14.008 14242 15626 W System.err: top=0, bottom=9
07-30 20:06:14.008 14242 15626 W System.err: n=1, l=9
07-30 20:06:14.008 14242 15626 W System.err: screenBase=0, windowBase=0
07-30 20:06:14.008 14242 15626 W System.err: newScreenBase=0, newWindowBase=0
07-30 20:06:14.008 14242 15626 W System.err: oldBase=0
07-30 20:06:14.008 14242 15626 W System.err: size.width=112, size.height=10
07-30 20:06:14.008 14242 15626 W System.err: abuf.length=25, cbuf.length=25
07-30 20:06:14.008 14242 15626 W System.err: *** done dumping debug information
07-30 20:06:14.867  1184  1237 W WindowManager: Unable to start animation, surface is null or no children.
07-30 20:06:15.011 14242 15626 W System.err: *** Error while scrolling up:
07-30 20:06:15.011 14242 15626 W System.err: --- BEGIN STACK TRACE ---
07-30 20:06:15.011 14242 15626 W System.err: java.lang.ArrayIndexOutOfBoundsException: src.length=25 srcPos=0 dst.length=25 dstPos=-1 length=1
07-30 20:06:15.012 14242 15626 W System.err: 	at java.lang.System.arraycopy(Native Method)
07-30 20:06:15.012 14242 15626 W System.err: 	at de.mud.terminal.VDUBuffer.insertLine(VDUBuffer.java:421)
07-30 20:06:15.012 14242 15626 W System.err: 	at de.mud.terminal.vt320.putChar(vt320.java:1733)
07-30 20:06:15.012 14242 15626 W System.err: 	at de.mud.terminal.vt320.putString(vt320.java:126)
07-30 20:06:15.012 14242 15626 W System.err: 	at de.mud.terminal.vt320.putString(vt320.java:80)
07-30 20:06:15.012 14242 15626 W System.err: 	at org.connectbot.service.TerminalBridge.outputLine(TerminalBridge.java:336)
07-30 20:06:15.012 14242 15626 W System.err: 	at org.connectbot.transport.SSH.authenticate(SSH.java:253)
07-30 20:06:15.012 14242 15626 W System.err: 	at org.connectbot.transport.SSH.connect(SSH.java:537)
07-30 20:06:15.012 14242 15626 W System.err: 	at org.connectbot.service.TerminalBridge$3.run(TerminalBridge.java:290)
07-30 20:06:15.013 14242 15626 W System.err: 	at java.lang.Thread.run(Thread.java:764)
07-30 20:06:15.013 14242 15626 W System.err: --- END STACK TRACE ---
07-30 20:06:15.013 14242 15626 W System.err: bufSize=25, maxBufSize=25
07-30 20:06:15.013 14242 15626 W System.err: top=0, bottom=9
07-30 20:06:15.013 14242 15626 W System.err: n=1, l=9
07-30 20:06:15.013 14242 15626 W System.err: screenBase=0, windowBase=0
07-30 20:06:15.013 14242 15626 W System.err: newScreenBase=0, newWindowBase=0
07-30 20:06:15.013 14242 15626 W System.err: oldBase=0
07-30 20:06:15.013 14242 15626 W System.err: size.width=112, size.height=10
07-30 20:06:15.013 14242 15626 W System.err: abuf.length=25, cbuf.length=25
07-30 20:06:15.013 14242 15626 W System.err: *** done dumping debug information
07-30 20:06:15.014 14242 15626 W System.err: *** Error while scrolling up:
07-30 20:06:15.014 14242 15626 W System.err: --- BEGIN STACK TRACE ---
07-30 20:06:15.014 14242 15626 W System.err: java.lang.ArrayIndexOutOfBoundsException: src.length=25 srcPos=0 dst.length=25 dstPos=-1 length=1
07-30 20:06:15.014 14242 15626 W System.err: 	at java.lang.System.arraycopy(Native Method)
07-30 20:06:15.014 14242 15626 W System.err: 	at de.mud.terminal.VDUBuffer.insertLine(VDUBuffer.java:421)
07-30 20:06:15.014 14242 15626 W System.err: 	at de.mud.terminal.vt320.putChar(vt320.java:1733)
07-30 20:06:15.014 14242 15626 W System.err: 	at de.mud.terminal.vt320.putString(vt320.java:126)
07-30 20:06:15.014 14242 15626 W System.err: 	at de.mud.terminal.vt320.putString(vt320.java:80)
07-30 20:06:15.014 14242 15626 W System.err: 	at org.connectbot.service.TerminalBridge.outputLine(TerminalBridge.java:336)
07-30 20:06:15.014 14242 15626 W System.err: 	at org.connectbot.transport.SSH.authenticate(SSH.java:321)
07-30 20:06:15.014 14242 15626 W System.err: 	at org.connectbot.transport.SSH.connect(SSH.java:537)
07-30 20:06:15.014 14242 15626 W System.err: 	at org.connectbot.service.TerminalBridge$3.run(TerminalBridge.java:290)
07-30 20:06:15.014 14242 15626 W System.err: 	at java.lang.Thread.run(Thread.java:764)
07-30 20:06:15.014 14242 15626 W System.err: --- END STACK TRACE ---
07-30 20:06:15.014 14242 15626 W System.err: bufSize=25, maxBufSize=25
07-30 20:06:15.014 14242 15626 W System.err: top=0, bottom=9
07-30 20:06:15.015 14242 15626 W System.err: n=1, l=9
07-30 20:06:15.015 14242 15626 W System.err: screenBase=0, windowBase=0
07-30 20:06:15.015 14242 15626 W System.err: newScreenBase=0, newWindowBase=0
07-30 20:06:15.015 14242 15626 W System.err: oldBase=0
07-30 20:06:15.015 14242 15626 W System.err: size.width=112, size.height=10
07-30 20:06:15.015 14242 15626 W System.err: abuf.length=25, cbuf.length=25
07-30 20:06:15.015 14242 15626 W System.err: *** done dumping debug information
```

**Comment by hagau** [comment] 2018-07-31 15:35
@colemickens Thanks for providing the stack trace :smiley:!  
I'm investigating now.

**Comment by hagau** [comment] 2018-08-01 15:35
Hm, this is interesting. The exceptions happen at different places (SSH.java:313,318,253,321) while authenticating, but I don't think it's authentication related since it happens *before* auth and *after* failed auth. This looks more obviously like an issue with the terminal drawing code.

@colemickens A couple of questions:
- Are you sure the target `sshd` is configured correctly? (I've locked myself out of a box due to a restrictive `sshd_config` more than once...). Does logging in with `ssh` using `gpg-agent` with the gpg key work maybe?
- Does the bug occur on every connection?

**Comment by Valodim** [comment] 2018-08-01 15:43
The stack traces are written from System.err, it's probably an unrelated expected exception somewhere that outputs some debug into in the catch clause.

**Comment by hagau** [comment] 2018-08-01 16:02
@Valodim Well, you're sort of right.  
https://github.com/open-keychain/termbot/blob/7d6d355ef449fe41ca96a6f7a1b4cee9860fe1e3/app/src/main/java/de/mud/terminal/VDUBuffer.java#L446 is the cause of the debug information. Looking at that, the exception should not result in a connection failure.

**Comment by hagau** [comment] 2018-08-03 13:36
I still have no idea why this happens, but I can see from the crash reports in the Google Play Console that there are a bunch of bugs that have not yet been addressed and which could lead to failed authentication. I'll look into those and maybe it'll solve this one, too.

**Comment by colemickens** [comment] 2018-08-04 00:22
Not sure if you still need these answers but:

1. Yes, I'm sure `sshd` is configured properly. I am able to use the yubikey to auth from Windows with WinSCP, from WSL, from my Linux boxes, etc. I have password auth disabled and no local private keys on my boxes, so I can be very sure that the yubikey auth should work. (I haven't attempted to run `gpg-agent` manually in Android, but if it would be useful, link me to instructions and I'll give it a shot.)

2. Yes, every connection.

If it helps, I am using subkeys -- the master private key is not stored on the Yubikey, only the subkeys' secrets. I am happy to provide any other logs/feedback, just let me know what would be helpful. If you have enough hints or have a Slack/IRC where we can chat, I'd be willing to install the Android SDK And debug through this too...

**Comment by hagau** [comment] 2018-08-04 16:10
@colemickens Thanks, I should have asked thos questions right at the start.  
Hm, I've found a crash report for a Pixel 2 on API 28 in the Play console; maybe that's it...

**Comment by nagromc** [comment] 2018-08-19 14:53
FYI, same exact result on Nexus 5X, Android 8.1.0 Stock with the latest security updates (5 August 2018).
Termbot version: 1.9.2-termbot.4
Physical token used: Yubikey NEO firmware v3.4.9

Though, I can:
- login from my laptop with the same Yubikey NEO (subkey A with authentication capabilities)
- sign/decrypt content from my smartphone using the same Yubikey NEO through NFC (subkeys B/C respectively with signing and encryption capabilities)

I can provide a stack trace if you need it.

**Comment by hagau** [comment] 2018-08-19 16:56
@nagromc That might be another issue actually, but a stack trace would be appreciated.  
Unfortunately, the error reporting to the user is rather limited; I'll improve that for the next release.

**Comment by hagau** [comment] 2018-08-28 11:38
I suspect this might be one of many issues with `targetSdkVersion` >25.
I'll do a beta release with `targetSdkVersion` lowered to 25 soonish.

**Comment by Valodim** [comment] 2018-08-28 11:41
Not sure that's a good idea: https://developer.android.com/distribute/best-practices/develop/target-sdk

**Comment by hagau** [comment] 2018-08-28 11:56
*"Google Play will require that new apps target at least Android 8.0 (API level 26) from August 1, 2018, and that app updates target Android 8.0 from November 1, 2018."*  

Hm, that gives me two months to fix the issues with background services with API level >25 :)
It's a temporary band-aid anyway, maybe I just do quick build and add it to the release page instead of going through the Play store.
I should have updated `targetSdkVersion` more carefully and slowly...

**Comment by tombriden** [comment] 2018-08-28 12:23
Hi, I'm also having this issue (Pixel 2 XL with Android 9.0.0) and I just compiled a build with targetSdkVersion set to 25 without success. I have it running through android studio so let me know if there's anything I can do to help debug this

**Comment by hagau** [comment] 2018-08-28 12:33
@tombriden *"without success"* meaning the issue prevails even with a build with `targetSdkVersion` set to 25? Hm...
If you could search the logs for anything interesting (exception?) happening when authentication fails, that would be appreciated.

**Comment by tombriden** [comment] 2018-08-28 12:49
Sorry I wasn't clear; even with `targetSdkVersion` set to 25 I'm getting `Failed to authenticate`.

The only error logged while authenticating is:
```
E/e.termbot.debu: Invalid ID 0x00000000.
```
and stepping through the code, starting at `AuthenticationManager.java:238`, everything looks fine but the first byte of the message returned from the server matches `SSH_MSG_USERAUTH_FAILURE`

**Comment by tombriden** [comment] 2018-08-28 12:51
...and actually, that error log line occurs after the server response has come through so I don't think it's relevant

**Comment by hagau** [comment] 2018-08-28 13:12
Hm, there should be an error message from `tryAgentAuthentication` in `SSH.java:418` in the log, at least with the latest git HEAD.  
Look for `"Couldn't authenticate via agent"` in the logs.

**Comment by tombriden** [comment] 2018-08-28 13:21
That's only logged if there's an exception thrown, but there isn't as it's a valid 'auth failed' response from the server, resulting in `isAuthenticationSuccessful` returning `false`

**Comment by hagau** [comment] 2018-08-28 13:34
That would point to either:
- the signature supplied by the agent being faulty
- the key not being allowed for that user

I can't think of anything else right now. Hm... :thinking:

**Comment by hagau** [comment] 2018-08-28 13:56
@tombriden thanks for your help by the way!

**Comment by tombriden** [comment] 2018-08-28 14:01
No problem :)

I think you're right about it being a faulty signature, starting my sshd with `-ddd` is logging:

```
debug3: mm_answer_keyallowed: publickey authentication: RSA key is allowed                                                                                                                                         
debug3: mm_request_send entering: type 23                                                                                                                                                                          
debug3: mm_sshkey_verify entering [preauth]                                                                                                                                                                        
debug3: mm_request_send entering: type 24 [preauth]                                                                                                                                                                
debug3: mm_sshkey_verify: waiting for MONITOR_ANS_KEYVERIFY [preauth]                                                                                                                                              
debug3: mm_request_receive_expect entering: type 25 [preauth]                                                                                                                                                      
debug3: mm_request_receive entering [preauth]                                                                                                                                                                      
debug3: mm_request_receive entering                                                                                                                                                                                
debug3: monitor_read: checking request 24                                                                                                                                                                          
debug3: mm_answer_keyverify: publickey 0x591560 signature unverified

```

so it's accepting the RSA key but can't verify the signature

**Comment by hagau** [comment] 2018-08-28 14:06
`signature unverified` pretty much means the signature is faulty, yes.

**Comment by tombriden** [comment] 2018-08-29 12:34
I'm quite keen to get this working so if you have any pointers for where to start digging I'm happy to spend some time looking into it. 
Do you know if this is limited to yubikey/smartcard authentication (sub)keys or do open-keychain generated keys not work either?

**Comment by tombriden** [comment] 2018-08-30 14:51
To answer my own question, I generated a key in open-keychain and added a new authentication sub-key to it. Same issue in term-bot using that key so it's still looking like something to do with either the authentication request or the signing of it and not to do with it being a yubikey key

**Comment by hagau** [comment] 2018-08-30 18:23
Sorry for the late reply, but right now I'm unsure how to proceed.
If there is a difference between smartcard and on-device keys, then that would point to an issue in OpenKeychain. I suspect that is not the case, since there are unit tests for the signature generation and encoding in OpenKeychain.
I'll try & find some pointers, but you might start by looking into `tryAgentAuthentication` in `SSH.java`, as you already did.
Hm, you could add
```
byte[] sig = RSASHA512Verify.decodeRSASHA512Signature(rsa_sig_enc);
boolean isValidSignature = RSASHA512Verify.verifySignature(msg, sig, (RSAPublicKey) publicKey);
System.out.println("========>>>>>>>>>>>>>>       isValidSignature = "+ isValidSignature);
```
after [AuthenticationManager.java:251](https://github.com/open-keychain/sshlib/blob/7a030b2519dbff8687a2c0d320b896397c7c0791/sshlib/src/main/java/com/trilead/ssh2/auth/AuthenticationManager.java#L251), to check if the signature (EDIT: provided by the agent) is actually valid. (EDIT: for `rsa-sha2-512` auth)

**Comment by tombriden** [comment] 2018-08-31 07:33
`verifySignature` returns true so at least the signing appears to be correct. I'm going to try hooking into the gpg-agent process and compare the data it signs with the data termbot is getting signed to see if anything's obviously different with it

**Comment by tombriden** [comment] 2018-08-31 13:16
I'm in! It appears the public key alogrithm in the authentication request and the data block that gets signed needs to actually be the signing algorithm, eg `rsa-sha2-512` instead of just `ssh-rsa`. 

Now, RFC4252 just calls this field the 'public algorithm name' rather than the 'public key signature algorithm' so it's not really that clear, but the openssh code uses the signature algorithm here so I think that must be correct; see:
https://github.com/openssh/openssh-portable/blob/master/sshconnect2.c#L1254 where it uses the variable `alg` for the 'public key algorithm name', which is set on line 1225 by calling function `key_sig_algorithm` that starts with the comment :
```
Select an algorithm for publickey signatures.
```



Edit: give me 10mins and I'll open a pull request

**Comment by hagau** [comment] 2018-08-31 16:44
@tombriden Thanks for your awesome work!
I remember verifying the RSA-SHA2 authentication methods when I merged them, and I remember being a bit confused about the signing algorithm tag, but after testing and reading RFCs I just accepted OpenSSH's behaviour. But back then OpenSSH was more liberal in what it accepted:  
[upstream: Improve strictness and control over RSA-SHA2 signature ](https://github.com/openssh/openssh-portable/commit/4ba0d54794814ec0de1ec87987d0c3b89379b436)

That should be in OpenSSH 7.8p (which was released on August 23; hm...)

**Comment by hagau** [comment] 2018-08-31 17:28
I'm running 7.7p1, Debian testing has 7.7p1, too. So that commit should not affect anyone (yet).
@tombriden Are you running 7.8p1?
 
I just checked and 7.7p1 allows usage of `rsa-sha2-512` tagged as `ssh-rsa`, which was the default behaviour in sshlib.

**Comment by tombriden** [comment] 2018-08-31 17:35
Yep, I'm on 7.8_p1

**Comment by colemickens** [comment] 2018-08-31 18:07
My `sshd` is `7.7_p1`. For me, however, the RSA SHA256 lines are different for me from using my laptop vs TermBot+OpenKeychain.

I have confirmed other things: the (sub)keyid shown in TermBot is the same subkey ID I see when I check `gpg --card-status` and `gpg --list-pubkeys --show-colons` (and it's the auth subkey). Also, I've run `ssh-add -L` to output my key, then manually converted it and checked that it should be the `DRLT...` seen below.

So it seems like TermBot/OpenKeychain is using/sending the wrong key/signature somehow?

Success:
```
Aug 31 11:03:17 chimera sshd[21068]: Connection from 192.168.1.1 port 44122 on 192.168.1.16 port 22
Aug 31 11:03:17 chimera sshd[21068]: Accepted key RSA SHA256:DRLTqHaHUaiBl7Gql+m7H+FW8+/oyxYeLgQYJyJ43mg found at /etc/ssh/authorized_keys.d/cole:1
Aug 31 11:03:17 chimera sshd[21068]: Postponed publickey for cole from 192.168.1.1 port 44122 ssh2 [preauth]
Aug 31 11:03:22 chimera sshd[21068]: Accepted key RSA SHA256:DRLTqHaHUaiBl7Gql+m7H+FW8+/oyxYeLgQYJyJ43mg found at /etc/ssh/authorized_keys.d/cole:1
Aug 31 11:03:22 chimera sshd[21068]: Accepted publickey for cole from 192.168.1.1 port 44122 ssh2: RSA SHA256:DRLTqHaHUaiBl7Gql+m7H+FW8+/oyxYeLgQYJyJ43mg
Aug 31 11:03:22 chimera sshd[21068]: pam_unix(sshd:session): session opened for user cole by (uid=0)
```

Failure:
```
Aug 31 11:00:14 chimera sshd[20912]: Connection from 192.168.1.1 port 47773 on 192.168.1.16 port 22
Aug 31 11:00:15 chimera sshd[20912]: Failed publickey for cole from 192.168.1.1 port 47773 ssh2: RSA SHA256:y1ukdxegRLSQphdz4gqAdK537aPNT3TZQWJnJuzSXBs
Aug 31 11:00:16 chimera sshd[20912]: error: PAM: Authentication failure for cole from 192.168.1.1
Aug 31 11:00:16 chimera sshd[20912]: Failed keyboard-interactive/pam for cole from 192.168.1.1 port 47773 ssh2
Aug 31 11:00:32 chimera sshd[20912]: Received disconnect from 192.168.1.1 port 47773:11: Closed due to user request. [preauth]
```

**Comment by hagau** [comment] 2018-08-31 18:22
@colemickens Hm, interresting. I'm guessing you're using the key for the mail address from your profile?

**Comment by hagau** [comment] 2018-08-31 18:49
@colemickens You're right. `gpg-agent` & OpenKeychain are picking different authentication subkeys. Your key has multiple authentication subkeys, and there is no support for selecting a specific subkey in OpenKeychain (yet).
To verify, try adding the other authentication subkeys to to the list of allowed keys.

**Comment by colemickens** [comment] 2018-09-01 02:22
I don't have the keys for the other auth subkeys anymore. They're not usable. Also, this must just be a bug somewhere right? `termbot` shows me the subkey ID that is selected for use with the agent and it's the correct subkey ID.

**Comment by michyprima** [comment] 2018-09-15 14:45
> To verify, try adding the other authentication subkeys to to the list of allowed keys.

I was having the same issue as @colemickens 
I verified deleting one of the two auth subkeys and re-importing my identity without the offending one and now termbot works just fine.

**Comment by Valodim** [comment] 2018-09-16 13:32
Did you get it to work with your patch?

**Comment by hagau** [comment] 2018-09-16 14:07
@Valodim What patch are you refering to?
Btw, I checked the key selection code in OpenKeychain and it picks the first key (that's ok) returned by sqlite (which should all be valid). I don't see how it can select a revoked key...  
I'll be looking into this this week with a couple of test keys, maybe write a test for keys with multiple (revoked) auth subkeys.

**Comment by michyprima** [comment] 2018-09-16 14:23
it's not ok, it should pick the key we selected in termbot simply because a token may not contain the private key it picks. that's exactly what's happening to me

my identity has multiple auth subkeys but only one is on a given token

edit not to mention the key it picks may not be authorized on the server

**Comment by colemickens** [comment] 2018-09-21 00:44
@hagau or others: What can be done to help move this along? I don't really want to workaround this by modifying my public key. If it's a simple addition, I'd like to make it. Especially since TermBot/OpenKeychain act as if this is already implemented, in that it shows the subkey id that it will use for auth (except that it doesn't *actually* use that one, as it is right now.)

**Comment by hagau** [comment] 2018-09-21 10:07
@colemickens Sorry, my investigation has not turned up anything yet, but I haven't found the time to construct a test key triggering the bug yet. It works fine with a key with multiple valid auth subkeys in my cursory experiments. I'll hopefully can get to that tonight.  

In any case, fully resolving this requires rewriting the key selection UI (which is neccessary anyway), implementing subkey selection in TermBot (~~a bit more tricky~~) and OpenKeychain's `SshAuthenticationService`. The ~~`sshauthentication-api` &~~ `AuthenticationOperation` already support subkey selection, so at least that's not an issue.
Right now, I don't know how much work this entails or the best approach. I'll report what I find over the weekend :)

**Comment by hagau** [comment] 2018-09-25 20:29
- (Ok, `sshauthentication-api` is supposed to be agnostic with regard to the key managment system used, so "*`sshauthentication-api` supports subkey selection*" is wrong)
- It seems TermBot doesn't need any modifications for subkey selection, at least I don't see anything yet. (Plenty of other stuff to do, though; patches welcome :)
- I've started implementing subkey selection for OpenKeychain; this should alleviate problems like this issue in the near future.

**Closed as completed** 2018-10-02 14:11 UTC

**Comment by Valodim** [comment] 2018-10-02 15:01
Use of expired or revoked subkeys should be fixed, see https://github.com/open-keychain/open-keychain/pull/2397. We'll release a beta of OpenKeychain with the fix soon.
